[project]
name = "graphene"
version = "0.1.0"
description = "Graphene real-time engine and editor"
readme = "README.md"
licence = "MIT"
build = "build.enq"
dependencies = ["index@json", "index@linalg", "path@../Luma/workspace/vulkan_native", "path@../Luma[fonts]"]
